on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: customerreg.azurecr.io
        username: ${{ secrets.acr_customerreg_username }}
        password: ${{ secrets.acr_customerreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t customerreg.azurecr.io/customeraks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push customerreg.azurecr.io/customeraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_customeraks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep customeraks9b1a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace customeraks9b1a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: customeraks9b1a
        container-registry-url: customerreg.azurecr.io
        container-registry-username: ${{ secrets.acr_customerreg_username }}
        container-registry-password: ${{ secrets.acr_customerreg_password }}
        secret-name: customeraksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: customeraks9b1a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          customerreg.azurecr.io/customeraks:${{ github.sha }}
        imagepullsecrets: |
          customeraksdockerauth
